/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectionFailedScreen.java
 *
 * Created on May 31, 2009, 5:03:55 PM
 */
package br.ita.ces31.imagelabeler.client.ui.screen;

import br.ita.ces31.ImageLabelerClient.ui.ConnectionFailedUI;

/**
 *
 * @author diego
 */
public class ConnectionFailedScreen extends javax.swing.JFrame {
    private ConnectionFailedUI connectionFailedUI = new ConnectionFailedUI(this);

    /** Creates new form ConnectionFailedScreen */
    public ConnectionFailedScreen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        lblVerifyConnectionMessage = new javax.swing.JLabel();
        lblConnectionFailedMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Labeler");

        btnOk.setText("ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblVerifyConnectionMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerifyConnectionMessage.setText("Verify your Internet connection or try again later!");
        lblVerifyConnectionMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblVerifyConnectionMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVerifyConnectionMessage.setMaximumSize(new java.awt.Dimension(300, 14));
        lblVerifyConnectionMessage.setPreferredSize(new java.awt.Dimension(300, 14));
        lblVerifyConnectionMessage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblConnectionFailedMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnectionFailedMessage.setText("Not possible to connect to the server!");
        lblConnectionFailedMessage.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConnectionFailedMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addComponent(lblVerifyConnectionMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConnectionFailedMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerifyConnectionMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        ok();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConnectionFailedScreen().setVisible(true);
            }
        });
    }

    private void ok() {
        getConnectionFailedUI().ok();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblConnectionFailedMessage;
    private javax.swing.JLabel lblVerifyConnectionMessage;
    // End of variables declaration//GEN-END:variables

    public ConnectionFailedUI getConnectionFailedUI() {
        return connectionFailedUI;
    }

    public void setConnectionFailedUI(ConnectionFailedUI connectionFailedUI) {
        this.connectionFailedUI = connectionFailedUI;
    }
}
