/*
 * Image Labeler - Projeto de CES-31
 */

/*
 * TestLoginScreen.java
 *
 * Created on May 10, 2009, 7:03:33 PM
 */
package br.ita.ces31.ImageLabelerClient.ui;

import br.ita.ces31.ImageLabelerClient.communicator.CommunicationException;
import br.ita.ces31.ImageLabelerClient.communicator.Communicator;
import br.ita.ces31.ImageLabelerClient.communicator.CommunicatorObserver;
import br.ita.ces31.ImageLabelerClient.communicator.CommunicatorSingleton;
import br.ita.ces31.ImageLabelerCommon.GameSummary;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Helder Suzuki <helder@aluno.ita.br>
 */
public class TestLoginScreen extends JFrame implements CommunicatorObserver {

    private Communicator communicator;

    /** Creates new form TestLoginScreen */
    public TestLoginScreen() throws CommunicationException {
        initComponents();
        communicator = CommunicatorSingleton.getCommunicator();
        communicator.addObserver(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        userNameField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        userNameField.setToolTipText("Your name");
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonAction(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(userNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(connectButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(userNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(connectButton))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_userNameFieldActionPerformed

    private void connectButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonAction
        try {
            login();
        } catch (CommunicationException ex) {
            Logger.getLogger(TestLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_connectButtonAction

    private void login() throws CommunicationException {
        System.out.println(userNameField.getText() + " connect!");
        communicator.identify(userNameField.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    public String getLoginName() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void notifyMatch(String match) {
        System.out.println("Match: " + match);
    }

    public void startGame(int seconds) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void endGame(GameSummary summary) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void engGameByPenico() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
